name: Deploy Azure Function

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'azureimgproc'
  RESOURCE_GROUP: 'imgprocessorazure'
  PYTHON_VERSION: '3.11'
  STORAGE_ACCOUNT: 'mynewstorageacc'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write  # ضروري لمصادقة OIDC

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'  # تفعيل الذاكرة المؤقتة لتسريع التثبيت

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --target="./.python_packages/lib/site-packages" -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create storage containers
        run: |
          az storage container create --name uploads --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
          az storage container create --name processed --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"

      - name: Deploy to Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: function_app/
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true

      - name: Verify deployment
        run: |
          echo "Deployment successful!"
          echo "Function App URL: https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net"
          curl -s https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/api/healthcheck | jq